/** Declaration file generated by dts-gen */

declare enum SORT_ORDER {
  ASC,
  DEC
}

export type GithubResponse = {
  id: number,
  avatar_url: string,
  url: string,
  description: string,
  open_issues_count: number,
  stargazers_count: number,
  created_at: number,
};

export function getForkedRepo(options: {
  order: SORT_ORDER,
  pageNo: number,
  sort: string,
  queryString: string
}): GithubResponse;